services:  

  zookeeper:
    container_name: zookeeper
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    networks:
      - my_network

  kafka:
    container_name: kafka
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
      - "9094:9094"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_LISTENERS: INTERNAL://0.0.0.0:9092,OUTSIDE://0.0.0.0:9094
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:9092,OUTSIDE://localhost:9094
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: true
    networks:
      - my_network

  control-center:
    container_name: control-center
    image: confluentinc/cp-enterprise-control-center:latest
    hostname: control-center
    depends_on:
      - kafka
    ports:
      - "9021:9021"
    environment:
      CONTROL_CENTER_BOOTSTRAP_SERVERS: 'kafka:9092'
      CONTROL_CENTER_REPLICATION_FACTOR: 1
      CONTROL_CENTER_CONNECT_CLUSTER: http://kafka-connect:8083
      PORT: 9021
    networks:
      - my_network

  redis:
    container_name: redis
    image: redis:latest
    ports:
      - "6380:6379"
    volumes:
      - redis-data:/data
    networks:
      - my_network

  sqlserver:
    container_name: sqlserver
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: "YourStrong!Passw0rd"
      ACCEPT_EULA: "Y"
    ports:
      - "14333:1433"
    volumes:
      - sqlserver-data:/var/opt/mssql
    networks:
      - my_network

  consolidation-worker:
    container_name: consolidation-worker
    image: leomarcamargo/consolidation-worker:latest
    depends_on:
      - sqlserver
      - kafka
      - redis
    environment:
      - ConnectionStrings__ConsolidationConnection=Server=sqlserver,1433;Database=Consolidation;User Id=sa;Password=YourStrong!Passw0rd;TrustServerCertificate=true;
      - KafkaSettings__BootstrapServers=kafka:9092
      - RedisSettings__Host=redis
      - RedisSettings__Port=6379
      - DOTNET_ENVIRONMENT=Development
    networks:
      - my_network
    entrypoint: ["sh", "-c", "sleep 30 && dotnet Consolidations.Worker.dll"]

  transaction-api:
    container_name: transaction-api
    image: leomarcamargo/transaction-api:latest
    depends_on:
      - sqlserver
      - kafka
      - redis
    environment:
      - ConnectionStrings__TransactionConnection=Server=sqlserver,1433;Database=Transaction;User Id=sa;Password=YourStrong!Passw0rd;TrustServerCertificate=true;
      - KafkaSettings__BootstrapServers=kafka:9092
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:7032
    ports:
      - "7033:7032"
    networks:
      - my_network
    entrypoint: ["sh", "-c", "sleep 30 && dotnet Transactions.API.dll"]

networks:
  my_network:
    driver: bridge

volumes:
  redis-data:
    driver: local
  sqlserver-data:
    driver: local